language: python
services: mysql
python:
  - 3.6
before_script:
  - cp owid_grapher/secret_settings.py.travis owid_grapher/secret_settings.py
  - mysql -e 'CREATE DATABASE test_grapher;'
script:
  - python manage.py test
notifications:
  email:
    - jaiden@mispy.me
