language: node_js
node_js:
  - "10"
services:
  - mysql
dist: xenial
sudo: required
before_script:
  - cp .env.travis .env
  - mysql -e 'CREATE DATABASE test_grapher;'
script:
  - yarn test
cache: yarn
notifications:
  email:
    recipients:
      - tech@ourworldindata.org
    on_success: never
    on_failure: always
