language: php
php:
  - 5.5.9
before_script:
  - cp .env.travis .env
  - composer install --no-interaction
  - mysql -e 'create database forge_test;'
script:
  - phpunit
notifications:
  email:
    - jaiden@mispy.me
