language: python
python:
  - 3.6
services:
  - mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
dist: trusty
sudo: required
before_script:
  - cp owid_grapher/secret_settings.py.travis owid_grapher/secret_settings.py
  - mysql -e 'CREATE DATABASE test_grapher;'
  - mkdir tmp
script:
  - python manage.py test
notifications:
  email:
    - jaiden@mispy.me
